version: '3.8'
services:
    avanza_front:
        container_name: sube_angular
        build:
           context: .
           dockerfile: Dockerfile
        ports:
           - 8080:80
        restart: always
        networks:
            - sube
networks:
     sube:
          external: true
